# Generated by Django 3.2.25 on 2024-09-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('C', 'Completado')], default='P', max_length=1),
        ),
    ]
