# Generated by Django 5.1 on 2024-09-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('C', 'Completada')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='M', max_length=1),
        ),
    ]
