# Generated by Django 5.1 on 2024-09-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_tarea_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
