# Generated by Django 5.0.6 on 2024-08-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='Tareas_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.tarea'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
