# Generated by Django 5.1 on 2024-08-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='fecha',
            field=models.DateField(),
        ),
    ]
