# Generated by Django 5.1 on 2024-08-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='reportes/')),
            ],
        ),
    ]
