# Generated by Django 5.0.6 on 2024-09-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='archivo',
            field=models.FileField(upload_to='Reporte/'),
        ),
    ]
