# Generated by Django 5.1 on 2024-09-07 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_alter_proyecto_fecha_inicio'),
        ('reporte', '0002_alter_reporte_archivo'),
        ('tareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='proyecto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='tareas',
            field=models.ManyToManyField(blank=True, to='tareas.tarea'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_comentario', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='reporte.reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
