# Generated by Django 5.0.6 on 2024-08-27 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.estado'),
        ),
    ]
