# Generated by Django 5.0.6 on 2024-08-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_estado_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
