# Generated by Django 5.1 on 2024-09-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_estado_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
