# Generated by Django 3.2.25 on 2024-09-05 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0004_alter_proyecto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='usuarios',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('C', 'Completado')], default='P', max_length=1),
        ),
    ]
