# Generated by Django 5.1 on 2024-09-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0006_remove_proyecto_estado_alter_proyecto_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En progreso'), ('C', 'Completado')], default='P', max_length=1),
        ),
    ]
