# Generated by Django 5.1 on 2024-09-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_alter_proyecto_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='equipo',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proyectos.equipo'),
            preserve_default=False,
        ),
    ]
